<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BudgetTableSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        DB::table('budget')->insert([
            [
                'dvNum' => 'DV30123',
                'accountID' => 'ACC32024',
                'programID' => 1,
                'controllerID' => 2,
                'drnNum' => 'DRN1234567890',
                'incomingDate' => '2024-08-25',
                'payee' => 'John Doe Enterprises',
                'particulars' => 'Office supplies purchase',
                'etal' => null,
                'program' => 'General Administration',
                'controller' => 'Jane Smith',
                'gross_amount' => 2500.00,
                'final_amount_norsa' => 2400.00,
                'fund_cluster' => '101',
                'appropriation' => 'General Expenses',
                'remarks' => 'Urgent delivery required',
                'orsNum' => 'ORS98765',
                'outgoingDate' => '2024-08-30',
                'status' => 'Pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'dvNum' => 'DV00144',
                'accountID' => 'ACCT2065',
                'programID' => 2,
                'controllerID' => 3,
                'drnNum' => 'DRN0987654321',
                'incomingDate' => '2024-09-01',
                'payee' => 'ABC Suppliers Inc.',
                'particulars' => 'IT Equipment purchase',
                'etal' => 'Includes installation',
                'program' => 'IT Support',
                'controller' => 'Alex Johnson',
                'gross_amount' => 5000.00,
                'final_amount_norsa' => 4900.00,
                'fund_cluster' => '102',
                'appropriation' => 'IT Expenses',
                'remarks' => 'Includes 3-year warranty',
                'orsNum' => 'ORS12345',
                'outgoingDate' => '2024-09-05',
                'status' => 'Completed',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'dvNum' => 'DV999',
                'accountID' => 'ACCT2065',
                'programID' => 2,
                'controllerID' => 3,
                'drnNum' => 'DRN0987654321',
                'incomingDate' => '2024-09-01',
                'payee' => 'ABC Suppliers Inc.',
                'particulars' => 'IT Equipment purchase',
                'etal' => 'Includes installation',
                'program' => 'IT Support',
                'controller' => 'Alex Johnson',
                'gross_amount' => 5000.00,
                'final_amount_norsa' => 4900.00,
                'fund_cluster' => '102',
                'appropriation' => 'IT Expenses',
                'remarks' => 'Includes 3-year warranty',
                'orsNum' => 'ORS12345',
                'outgoingDate' => '2024-09-05',
                'status' => 'Completed',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'dvNum' => 'DV788844',
                'accountID' => 'ACCT2065',
                'programID' => 2,
                'controllerID' => 3,
                'drnNum' => 'DRN0987654321',
                'incomingDate' => '2024-09-01',
                'payee' => 'ABC Suppliers Inc.',
                'particulars' => 'IT Equipment purchase',
                'etal' => 'Includes installation',
                'program' => 'IT Support',
                'controller' => 'Alex Johnson',
                'gross_amount' => 5000.00,
                'final_amount_norsa' => 4900.00,
                'fund_cluster' => '102',
                'appropriation' => 'IT Expenses',
                'remarks' => 'Includes 3-year warranty',
                'orsNum' => 'ORS12345',
                'outgoingDate' => '2024-09-05',
                'status' => 'Completed',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'dvNum' => 'DV7898989',
                'accountID' => 'ACCT2065',
                'programID' => 2,
                'controllerID' => 3,
                'drnNum' => 'DRN0987654321',
                'incomingDate' => '2024-09-01',
                'payee' => 'ABC Suppliers Inc.',
                'particulars' => 'IT Equipment purchase',
                'etal' => 'Includes installation',
                'program' => 'IT Support',
                'controller' => 'Alex Johnson',
                'gross_amount' => 5000.00,
                'final_amount_norsa' => 4900.00,
                'fund_cluster' => '102',
                'appropriation' => 'IT Expenses',
                'remarks' => 'Includes 3-year warranty',
                'orsNum' => 'ORS12345',
                'outgoingDate' => '2024-09-05',
                'status' => 'Completed',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'dvNum' => 'DV788844',
                'accountID' => 'ACCT2065',
                'programID' => 2,
                'controllerID' => 3,
                'drnNum' => 'DRN0987654321',
                'incomingDate' => '2024-09-01',
                'payee' => 'ABC Suppliers Inc.',
                'particulars' => 'IT Equipment purchase',
                'etal' => 'Includes installation',
                'program' => 'IT Support',
                'controller' => 'Alex Johnson',
                'gross_amount' => 5000.00,
                'final_amount_norsa' => 4900.00,
                'fund_cluster' => '102',
                'appropriation' => 'IT Expenses',
                'remarks' => 'Includes 3-year warranty',
                'orsNum' => 'ORS12345',
                'outgoingDate' => '2024-09-05',
                'status' => 'Completed',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'dvNum' => 'DV788444',
                'accountID' => 'ACCT2065',
                'programID' => 2,
                'controllerID' => 3,
                'drnNum' => 'DRN0987654321',
                'incomingDate' => '2024-09-01',
                'payee' => 'ABC Suppliers Inc.',
                'particulars' => 'IT Equipment purchase',
                'etal' => 'Includes installation',
                'program' => 'IT Support',
                'controller' => 'Alex Johnson',
                'gross_amount' => 5000.00,
                'final_amount_norsa' => 4900.00,
                'fund_cluster' => '102',
                'appropriation' => 'IT Expenses',
                'remarks' => 'Includes 3-year warranty',
                'orsNum' => 'ORS12345',
                'outgoingDate' => '2024-09-05',
                'status' => 'Completed',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'dvNum' => 'DV11111',
                'accountID' => 'ACCT2065',
                'programID' => 2,
                'controllerID' => 3,
                'drnNum' => 'DRN0987654321',
                'incomingDate' => '2024-09-01',
                'payee' => 'ABC Suppliers Inc.',
                'particulars' => 'IT Equipment purchase',
                'etal' => 'Includes installation',
                'program' => 'IT Support',
                'controller' => 'Alex Johnson',
                'gross_amount' => 5000.00,
                'final_amount_norsa' => 4900.00,
                'fund_cluster' => '102',
                'appropriation' => 'IT Expenses',
                'remarks' => 'Includes 3-year warranty',
                'orsNum' => 'ORS12345',
                'outgoingDate' => '2024-09-05',
                'status' => 'Completed',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'dvNum' => 'DV72222',
                'accountID' => 'ACCT2065',
                'programID' => 2,
                'controllerID' => 3,
                'drnNum' => 'DRN0987654321',
                'incomingDate' => '2024-09-01',
                'payee' => 'ABC Suppliers Inc.',
                'particulars' => 'IT Equipment purchase',
                'etal' => 'Includes installation',
                'program' => 'IT Support',
                'controller' => 'Alex Johnson',
                'gross_amount' => 5000.00,
                'final_amount_norsa' => 4900.00,
                'fund_cluster' => '102',
                'appropriation' => 'IT Expenses',
                'remarks' => 'Includes 3-year warranty',
                'orsNum' => 'ORS12345',
                'outgoingDate' => '2024-09-05',
                'status' => 'Completed',
                'created_at' => now(),
                'updated_at' => now(),
            ]

            // Add more sample entries as neededa
        ]);
    }
}

