<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class CashTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
       DB::table('cash')->insert([
            [
                'date_received' => Carbon::now(),
                'dvNum' => 'DV001',
                'payment_type' => 'Cheque',
                'check_ada_no' => 'CH123456',
                'gross_amount' => 1000.00,
                'net_amount' => 950.00,
                'final_net_amount' => 940.00,
                'date_issued' => Carbon::now(),
                'receipt_no' => 'RC001',
                'remarks' => 'Payment for supplies',
                'outgoing_date' => Carbon::now()->addDays(5),
                'action' => 'Approved',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'date_received' => Carbon::now(),
                'dvNum' => 'DV002',
                'payment_type' => 'ADA',
                'check_ada_no' => 'ADA654321',
                'gross_amount' => 2000.00,
                'net_amount' => 1900.00,
                'final_net_amount' => 1880.00,
                'date_issued' => Carbon::now(),
                'receipt_no' => 'RC002',
                'remarks' => 'Payment for services',
                'outgoing_date' => Carbon::now()->addDays(7),
                'action' => 'Pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'date_received' => Carbon::now(),
                'dvNum' => 'DV002',
                'payment_type' => 'ADA',
                'check_ada_no' => 'ADA654321',
                'gross_amount' => 2000.00,
                'net_amount' => 1900.00,
                'final_net_amount' => 1880.00,
                'date_issued' => Carbon::now()->subDays(10),
                'receipt_no' => 'RC002',
                'remarks' => 'Payment for equipment',
                'outgoing_date' => Carbon::now()->addDays(7),
                'action' => 'Pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'date_received' => Carbon::now(),
                'dvNum' => 'DV003',
                'payment_type' => 'Cheque',
                'check_ada_no' => 'CH789012',
                'gross_amount' => 1500.00,
                'net_amount' => 1400.00,
                'final_net_amount' => 1380.00,
                'date_issued' => Carbon::now()->subDays(3),
                'receipt_no' => 'RC003',
                'remarks' => 'Payment for services',
                'outgoing_date' => Carbon::now()->addDays(3),
                'action' => 'Denied',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'date_received' => Carbon::now(),
                'dvNum' => 'DV0076',
                'payment_type' => 'ADA',
                'check_ada_no' => 'ADA987654',
                'gross_amount' => 2500.00,
                'net_amount' => 2400.00,
                'final_net_amount' => 2380.00,
                'date_issued' => Carbon::now()->subDays(15),
                'receipt_no' => 'RC004',
                'remarks' => 'Payment for consultancy',
                'outgoing_date' => Carbon::now()->addDays(10),
                'action' => 'Approved',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'date_received' => Carbon::now(),
                'dvNum' => 'DV054',
                'payment_type' => 'ADA',
                'check_ada_no' => 'ADA987654',
                'gross_amount' => 2500.00,
                'net_amount' => 2400.00,
                'final_net_amount' => 2380.00,
                'date_issued' => Carbon::now()->subDays(15),
                'receipt_no' => 'RC004',
                'remarks' => 'Payment for consultancy',
                'outgoing_date' => Carbon::now()->addDays(10),
                'action' => 'Approved',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'date_received' => Carbon::now(),
                'dvNum' => 'DV0023',
                'payment_type' => 'ADA',
                'check_ada_no' => 'ADA987654',
                'gross_amount' => 2500.00,
                'net_amount' => 2400.00,
                'final_net_amount' => 2380.00,
                'date_issued' => Carbon::now()->subDays(15),
                'receipt_no' => 'RC004',
                'remarks' => 'Payment for consultancy',
                'outgoing_date' => Carbon::now()->addDays(10),
                'action' => 'Approved',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'date_received' => Carbon::now(),
                'dvNum' => 'DV0054',
                'payment_type' => 'ADA',
                'check_ada_no' => 'ADA987654',
                'gross_amount' => 2500.00,
                'net_amount' => 2400.00,
                'final_net_amount' => 2380.00,
                'date_issued' => Carbon::now()->subDays(15),
                'receipt_no' => 'RC004',
                'remarks' => 'Payment for consultancy',
                'outgoing_date' => Carbon::now()->addDays(10),
                'action' => 'Approved',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'date_received' => Carbon::now(),
                'dvNum' => 'DV098',
                'payment_type' => 'ADA',
                'check_ada_no' => 'ADA987654',
                'gross_amount' => 2500.00,
                'net_amount' => 2400.00,
                'final_net_amount' => 2380.00,
                'date_issued' => Carbon::now()->subDays(15),
                'receipt_no' => 'RC004',
                'remarks' => 'Payment for consultancy',
                'outgoing_date' => Carbon::now()->addDays(10),
                'action' => 'Approved',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'date_received' => Carbon::now(),
                'dvNum' => 'DV067',
                'payment_type' => 'ADA',
                'check_ada_no' => 'ADA987654',
                'gross_amount' => 2500.00,
                'net_amount' => 2400.00,
                'final_net_amount' => 2380.00,
                'date_issued' => Carbon::now()->subDays(15),
                'receipt_no' => 'RC004',
                'remarks' => 'Payment for consultancy',
                'outgoing_date' => Carbon::now()->addDays(10),
                'action' => 'Approved',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'date_received' => Carbon::now(),
                'dvNum' => 'DV058',
                'payment_type' => 'ADA',
                'check_ada_no' => 'ADA987654',
                'gross_amount' => 2500.00,
                'net_amount' => 2400.00,
                'final_net_amount' => 2380.00,
                'date_issued' => Carbon::now()->subDays(15),
                'receipt_no' => 'RC004',
                'remarks' => 'Payment for consultancy',
                'outgoing_date' => Carbon::now()->addDays(10),
                'action' => 'Approved',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'date_received' => Carbon::now(),
                'dvNum' => 'DV067',
                'payment_type' => 'ADA',
                'check_ada_no' => 'ADA987654',
                'gross_amount' => 2500.00,
                'net_amount' => 2400.00,
                'final_net_amount' => 2380.00,
                'date_issued' => Carbon::now()->subDays(15),
                'receipt_no' => 'RC004',
                'remarks' => 'Payment for consultancy',
                'outgoing_date' => Carbon::now()->addDays(10),
                'action' => 'Approved',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'date_received' => Carbon::now(),
                'dvNum' => 'DV031',
                'payment_type' => 'ADA',
                'check_ada_no' => 'ADA987654',
                'gross_amount' => 2500.00,
                'net_amount' => 2400.00,
                'final_net_amount' => 2380.00,
                'date_issued' => Carbon::now()->subDays(15),
                'receipt_no' => 'RC004',
                'remarks' => 'Payment for consultancy',
                'outgoing_date' => Carbon::now()->addDays(10),
                'action' => 'Approved',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'date_received' => Carbon::now(),
                'dvNum' => 'DV0211',
                'payment_type' => 'ADA',
                'check_ada_no' => 'ADA987654',
                'gross_amount' => 2500.00,
                'net_amount' => 2400.00,
                'final_net_amount' => 2380.00,
                'date_issued' => Carbon::now()->subDays(15),
                'receipt_no' => 'RC004',
                'remarks' => 'Payment for consultancy',
                'outgoing_date' => Carbon::now()->addDays(10),
                'action' => 'Approved',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'date_received' => Carbon::now(),
                'dvNum' => 'DV012',
                'payment_type' => 'ADA',
                'check_ada_no' => 'ADA987654',
                'gross_amount' => 2500.00,
                'net_amount' => 2400.00,
                'final_net_amount' => 2380.00,
                'date_issued' => Carbon::now()->subDays(15),
                'receipt_no' => 'RC004',
                'remarks' => 'Payment for consultancy',
                'outgoing_date' => Carbon::now()->addDays(10),
                'action' => 'Approved',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Add more sample data as needed
            ]);
    }
}
